# Experiment 1: Command Interface Tuning
## Setup
- Launch analysis nodes
    - scene est
    - 

## Analysis

In [1]:
# Imports
import os

import numpy as np

import rosbag2_py
from rclpy.serialization import deserialize_message
from rosidl_runtime_py.utilities import get_message

import rclpy
from rclpy.node import Node

from situated_hri_interfaces.srv import SceneVisRec, SceneAudioRec

In [2]:
# Parameters
filepath = '../../bags/e1_est_tuning'

In [3]:
# Member variables
rclpy.init()
node = Node('analysis_script_node')
clip_scene_rec_client = node.create_client(SceneVisRec, 'scene_vis_rec_service')
audio_scene_rec_client = node.create_client(SceneAudioRec, 'scene_audio_rec_service')

# scene recognition models
actual_scene_labels = ['campus','courtyard','lab','lobby']

clip_scene_labels = ['college-campus','courtyard','laboratory','lobby']
clip_scene_model = np.zeros((len(actual_scene_labels),len(clip_scene_labels)))

cpjku_audio_scene_labels = ['airport', 'bus', 'metro', 'metro_station', 'park', 'public_square', 'shopping_mall', 'street_pedestrian', 'street_traffic', 'tram']
cpjku_audio_scene_model = np.zeros((len(actual_scene_labels),len(cpjku_audio_scene_labels)))

# Member functions
def typename(topic_name):
    for topic_type in topic_types:
        if topic_type.name == topic_name:
            return topic_type.type
    raise ValueError(f"topic {topic_name} not in bag")

In [4]:
# Traverse filepath
for root, dirs, files in os.walk(filepath):

    # Examine each file
    for file in files:
        
        # If it is an mcap, examine
        if os.path.splitext(file)[-1] == '.mcap':

            # Get labels based on filepath
            labels = os.path.normpath(root).split(os.sep)
            command_actual = labels[-1]
            modality_actual = labels[-2]
            role_actual = labels[-3]
            scene_actual = labels[-4]

            scene_actual_idx = actual_scene_labels.index(scene_actual)
            
            print('Command: %s\nModality: %s\nRole: %s\nScene: %s (%s)\n\n' % (command_actual, modality_actual, role_actual, scene_actual, scene_actual_idx))
            
            reader = rosbag2_py.SequentialReader()            
            reader.open(
                rosbag2_py.StorageOptions(uri=os.path.join(root,file), storage_id="mcap"),
                rosbag2_py.ConverterOptions(
                    input_serialization_format="cdr", output_serialization_format="cdr"
                ),
            )
            topic_types = reader.get_all_topics_and_types()

            # Iterate through messages
            while reader.has_next():
                topic, data, timestamp = reader.read_next()
                msg_type = get_message(typename(topic))

                # Handle audio scene data
                if topic=='/audio_data':
                    audio_scene_req = SceneAudioRec.Request()
                    audio_scene_req.scene_audio = deserialize_message(data,msg_type)
                    future = audio_scene_rec_client.call_async(audio_scene_req)
                    rclpy.spin_until_future_complete(node, future)
                    
                    est_scene_idx = np.argmax(future.result().scene_class.probabilities)
                    cpjku_audio_scene_model[scene_actual_idx,est_scene_idx] += 1
                
                # Handle visual scene data
                if topic=='/oak/rgb/image_raw':
                    clip_scene_img_req = SceneVisRec.Request()
                    clip_scene_img_req.scene_image = deserialize_message(data,msg_type)
                    future = clip_scene_rec_client.call_async(clip_scene_img_req)
                    rclpy.spin_until_future_complete(node, future)
                    
                    est_scene_idx = np.argmax(future.result().scene_class.probabilities)
                    clip_scene_model[scene_actual_idx,est_scene_idx] += 1

            print("CLIP SCENE OBSERVATION MODEL")
            print(clip_scene_model)
            print("\n")

            print("DPJKU AUDIO SCENE OBSERVATION MODEL")
            print(cpjku_audio_scene_model)
            print("\n")

            del reader

# Cleanup
rclpy.shutdown()

Command: move-in-reverse
Modality: gest_verb
Role: supervisor
Scene: lab (2)


CLIP SCENE OBSERVATION MODEL
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0. 72. 25.]
 [ 0.  0.  0.  0.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Command: move-in-reverse
Modality: gest_verb
Role: supervisor
Scene: lab (2)


CLIP SCENE OBSERVATION MODEL
[[  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0. 151.  47.]
 [  0.   0.   0.   0.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 5. 1. 0. 0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Command: move-in-reverse
Modality: gest_verb
Role: supervisor
Scene: lab (2)


CLIP SCENE OBSERVATION MODEL
[[  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0. 243.  63.]
 [  0.   0.   0.   0.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 

[WARN] [1723075699.901780988] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[4.0920e+03 2.2000e+01 0.0000e+00 2.8680e+03]
 [4.1097e+04 1.7570e+03 0.0000e+00 5.3000e+01]
 [0.0000e+00 0.0000e+00 2.5793e+04 1.6399e+04]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[5.000e+00 1.000e+00 1.200e+01 0.000e+00 2.900e+01 0.000e+00 0.000e+00
  0.000e+00 4.000e+00 3.690e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: move-in-reverse
Modality: verbal
Role: supervisor
Scene: campus (0)




[WARN] [1723075702.520853194] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[4.1010e+03 2.2000e+01 0.0000e+00 2.8680e+03]
 [4.1097e+04 1.7570e+03 0.0000e+00 5.3000e+01]
 [0.0000e+00 0.0000e+00 2.5793e+04 1.6399e+04]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[5.000e+00 1.000e+00 1.200e+01 0.000e+00 2.900e+01 0.000e+00 0.000e+00
  0.000e+00 4.000e+00 3.690e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: move-in-reverse
Modality: verbal
Role: supervisor
Scene: campus (0)




[WARN] [1723075702.906618688] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[4.1070e+03 2.2000e+01 0.0000e+00 2.8680e+03]
 [4.1097e+04 1.7570e+03 0.0000e+00 5.3000e+01]
 [0.0000e+00 0.0000e+00 2.5793e+04 1.6399e+04]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[5.000e+00 1.000e+00 1.200e+01 0.000e+00 2.900e+01 0.000e+00 0.000e+00
  0.000e+00 4.000e+00 3.690e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: move-in-reverse
Modality: verbal
Role: supervisor
Scene: campus (0)




[WARN] [1723075703.226082872] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[4.1110e+03 2.2000e+01 0.0000e+00 2.8690e+03]
 [4.1097e+04 1.7570e+03 0.0000e+00 5.3000e+01]
 [0.0000e+00 0.0000e+00 2.5793e+04 1.6399e+04]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[5.000e+00 1.000e+00 1.200e+01 0.000e+00 2.900e+01 0.000e+00 0.000e+00
  0.000e+00 5.000e+00 3.690e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: move-forward
Modality: verbal
Role: supervisor
Scene: campus (0)




[WARN] [1723075705.475682002] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[4.1300e+03 2.2000e+01 0.0000e+00 2.8690e+03]
 [4.1097e+04 1.7570e+03 0.0000e+00 5.3000e+01]
 [0.0000e+00 0.0000e+00 2.5793e+04 1.6399e+04]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[5.000e+00 1.000e+00 1.200e+01 0.000e+00 2.900e+01 0.000e+00 0.000e+00
  0.000e+00 5.000e+00 3.700e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: move-forward
Modality: verbal
Role: supervisor
Scene: campus (0)




[WARN] [1723075706.460936637] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[4.1460e+03 2.2000e+01 0.0000e+00 2.8700e+03]
 [4.1097e+04 1.7570e+03 0.0000e+00 5.3000e+01]
 [0.0000e+00 0.0000e+00 2.5793e+04 1.6399e+04]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[5.000e+00 1.000e+00 1.200e+01 0.000e+00 2.900e+01 0.000e+00 0.000e+00
  0.000e+00 5.000e+00 3.720e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: move-forward
Modality: verbal
Role: supervisor
Scene: campus (0)




[WARN] [1723075707.419723105] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[4.1600e+03 2.3000e+01 0.0000e+00 2.8740e+03]
 [4.1097e+04 1.7570e+03 0.0000e+00 5.3000e+01]
 [0.0000e+00 0.0000e+00 2.5793e+04 1.6399e+04]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[5.000e+00 1.000e+00 1.200e+01 0.000e+00 2.900e+01 0.000e+00 0.000e+00
  1.000e+00 5.000e+00 3.720e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: move-forward
Modality: verbal
Role: supervisor
Scene: campus (0)




[WARN] [1723075711.381931262] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[4.1750e+03 2.3000e+01 0.0000e+00 2.8740e+03]
 [4.1097e+04 1.7570e+03 0.0000e+00 5.3000e+01]
 [0.0000e+00 0.0000e+00 2.5793e+04 1.6399e+04]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[5.000e+00 1.000e+00 1.200e+01 0.000e+00 2.900e+01 0.000e+00 0.000e+00
  1.000e+00 5.000e+00 3.730e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: move-forward
Modality: verbal
Role: supervisor
Scene: campus (0)




[WARN] [1723075714.609252828] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[4.1980e+03 2.3000e+01 0.0000e+00 2.8740e+03]
 [4.1097e+04 1.7570e+03 0.0000e+00 5.3000e+01]
 [0.0000e+00 0.0000e+00 2.5793e+04 1.6399e+04]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[5.000e+00 1.000e+00 1.200e+01 0.000e+00 2.900e+01 0.000e+00 0.000e+00
  1.000e+00 5.000e+00 3.740e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: follow-me
Modality: verbal
Role: supervisor
Scene: campus (0)


CLIP SCENE OBSERVATION MODEL
[[4.2860e+03 2.3000e+01 0.0000e+00 2.8760e+03]
 [4.1097e+04 1.7570e+03 0.0000e+00 5.3000e+01]
 [0.0000e+00 0.0000e+00 2.5793e+04 1.6399e+04]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00]]


DPJKU AUDIO SCENE OBSERVATIO

[WARN] [1723075822.761541892] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[4.7330e+03 2.3000e+01 0.0000e+00 2.8830e+03]
 [4.1097e+04 1.7570e+03 0.0000e+00 5.3000e+01]
 [0.0000e+00 0.0000e+00 2.5793e+04 1.6399e+04]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[5.000e+00 2.000e+00 1.600e+01 2.000e+00 3.000e+01 0.000e+00 0.000e+00
  1.000e+00 5.000e+00 3.980e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: rally
Modality: verbal
Role: supervisor
Scene: campus (0)




[WARN] [1723075826.248375153] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[4.7690e+03 2.3000e+01 0.0000e+00 2.8830e+03]
 [4.1097e+04 1.7570e+03 0.0000e+00 5.3000e+01]
 [0.0000e+00 0.0000e+00 2.5793e+04 1.6399e+04]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[5.000e+00 2.000e+00 1.700e+01 2.000e+00 3.000e+01 0.000e+00 0.000e+00
  1.000e+00 5.000e+00 4.000e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: rally
Modality: verbal
Role: supervisor
Scene: campus (0)




[WARN] [1723075828.903300440] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[4.8130e+03 2.3000e+01 0.0000e+00 2.8830e+03]
 [4.1097e+04 1.7570e+03 0.0000e+00 5.3000e+01]
 [0.0000e+00 0.0000e+00 2.5793e+04 1.6399e+04]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[5.000e+00 2.000e+00 1.700e+01 2.000e+00 3.000e+01 0.000e+00 0.000e+00
  1.000e+00 5.000e+00 4.020e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: rally
Modality: verbal
Role: supervisor
Scene: campus (0)




[WARN] [1723075837.593604254] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[4.8500e+03 2.4000e+01 0.0000e+00 2.8830e+03]
 [4.1097e+04 1.7570e+03 0.0000e+00 5.3000e+01]
 [0.0000e+00 0.0000e+00 2.5793e+04 1.6399e+04]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[5.000e+00 2.000e+00 1.800e+01 2.000e+00 3.000e+01 0.000e+00 0.000e+00
  1.000e+00 5.000e+00 4.040e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: rally
Modality: verbal
Role: supervisor
Scene: campus (0)




[WARN] [1723075844.306322393] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[4.8960e+03 2.4000e+01 0.0000e+00 2.8830e+03]
 [4.1097e+04 1.7570e+03 0.0000e+00 5.3000e+01]
 [0.0000e+00 0.0000e+00 2.5793e+04 1.6399e+04]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[5.000e+00 2.000e+00 1.900e+01 2.000e+00 3.000e+01 0.000e+00 0.000e+00
  1.000e+00 5.000e+00 4.050e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: halt
Modality: verbal
Role: supervisor
Scene: campus (0)


CLIP SCENE OBSERVATION MODEL
[[4.9700e+03 2.4000e+01 0.0000e+00 2.9120e+03]
 [4.1097e+04 1.7570e+03 0.0000e+00 5.3000e+01]
 [0.0000e+00 0.0000e+00 2.5793e+04 1.6399e+04]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00]]


DPJKU AUDIO SCENE OBSERVATION MOD

[WARN] [1723075859.662122751] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[5.0730e+03 2.4000e+01 0.0000e+00 2.9120e+03]
 [4.1097e+04 1.7570e+03 0.0000e+00 5.3000e+01]
 [0.0000e+00 0.0000e+00 2.5793e+04 1.6399e+04]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[5.000e+00 2.000e+00 2.100e+01 4.000e+00 3.000e+01 0.000e+00 0.000e+00
  1.000e+00 6.000e+00 4.130e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: halt
Modality: verbal
Role: supervisor
Scene: campus (0)


CLIP SCENE OBSERVATION MODEL
[[5.1750e+03 2.4000e+01 0.0000e+00 2.9140e+03]
 [4.1097e+04 1.7570e+03 0.0000e+00 5.3000e+01]
 [0.0000e+00 0.0000e+00 2.5793e+04 1.6399e+04]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00]]


DPJKU AUDIO SCENE OBSERVATION MOD

[WARN] [1723075927.084442866] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[5.4340e+03 2.4000e+01 0.0000e+00 2.9140e+03]
 [4.1097e+04 1.7570e+03 0.0000e+00 5.3000e+01]
 [0.0000e+00 0.0000e+00 2.5793e+04 1.6399e+04]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[5.000e+00 2.000e+00 2.100e+01 4.000e+00 3.100e+01 0.000e+00 0.000e+00
  1.000e+00 6.000e+00 4.320e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: advance
Modality: verbal
Role: supervisor
Scene: campus (0)




[WARN] [1723075929.780461661] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[5.4840e+03 2.4000e+01 0.0000e+00 2.9150e+03]
 [4.1097e+04 1.7570e+03 0.0000e+00 5.3000e+01]
 [0.0000e+00 0.0000e+00 2.5793e+04 1.6399e+04]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[5.000e+00 2.000e+00 2.200e+01 4.000e+00 3.100e+01 0.000e+00 0.000e+00
  1.000e+00 7.000e+00 4.330e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: advance
Modality: verbal
Role: supervisor
Scene: campus (0)




[WARN] [1723075937.696228065] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[5.5430e+03 2.5000e+01 0.0000e+00 2.9150e+03]
 [4.1097e+04 1.7570e+03 0.0000e+00 5.3000e+01]
 [0.0000e+00 0.0000e+00 2.5793e+04 1.6399e+04]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[5.000e+00 2.000e+00 2.400e+01 4.000e+00 3.100e+01 0.000e+00 0.000e+00
  1.000e+00 7.000e+00 4.350e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: advance
Modality: verbal
Role: supervisor
Scene: campus (0)




[WARN] [1723075946.566319082] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[5.5990e+03 2.5000e+01 0.0000e+00 2.9150e+03]
 [4.1097e+04 1.7570e+03 0.0000e+00 5.3000e+01]
 [0.0000e+00 0.0000e+00 2.5793e+04 1.6399e+04]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[5.000e+00 2.000e+00 2.500e+01 4.000e+00 3.100e+01 0.000e+00 0.000e+00
  1.000e+00 7.000e+00 4.370e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: advance
Modality: verbal
Role: supervisor
Scene: campus (0)




[WARN] [1723075961.383680999] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[5.6490e+03 2.6000e+01 0.0000e+00 2.9150e+03]
 [4.1097e+04 1.7570e+03 0.0000e+00 5.3000e+01]
 [0.0000e+00 0.0000e+00 2.5793e+04 1.6399e+04]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[5.000e+00 2.000e+00 2.500e+01 4.000e+00 3.100e+01 0.000e+00 0.000e+00
  1.000e+00 7.000e+00 4.400e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: attention
Modality: verbal
Role: supervisor
Scene: campus (0)




[WARN] [1723075970.504398635] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[5.6860e+03 2.7000e+01 0.0000e+00 2.9150e+03]
 [4.1097e+04 1.7570e+03 0.0000e+00 5.3000e+01]
 [0.0000e+00 0.0000e+00 2.5793e+04 1.6399e+04]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[5.000e+00 2.000e+00 2.500e+01 4.000e+00 3.100e+01 0.000e+00 0.000e+00
  1.000e+00 7.000e+00 4.430e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: attention
Modality: verbal
Role: supervisor
Scene: campus (0)




[WARN] [1723075976.783638987] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[5.7130e+03 2.8000e+01 0.0000e+00 2.9150e+03]
 [4.1097e+04 1.7570e+03 0.0000e+00 5.3000e+01]
 [0.0000e+00 0.0000e+00 2.5793e+04 1.6399e+04]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[5.000e+00 2.000e+00 2.500e+01 4.000e+00 3.100e+01 0.000e+00 0.000e+00
  1.000e+00 7.000e+00 4.450e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: attention
Modality: verbal
Role: supervisor
Scene: campus (0)




[WARN] [1723075980.174987286] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[5.7490e+03 2.9000e+01 0.0000e+00 2.9150e+03]
 [4.1097e+04 1.7570e+03 0.0000e+00 5.3000e+01]
 [0.0000e+00 0.0000e+00 2.5793e+04 1.6399e+04]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[5.000e+00 2.000e+00 2.500e+01 4.000e+00 3.100e+01 0.000e+00 0.000e+00
  1.000e+00 7.000e+00 4.480e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: attention
Modality: verbal
Role: supervisor
Scene: campus (0)




[WARN] [1723075991.272142489] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[5.7770e+03 2.9000e+01 0.0000e+00 2.9150e+03]
 [4.1097e+04 1.7570e+03 0.0000e+00 5.3000e+01]
 [0.0000e+00 0.0000e+00 2.5793e+04 1.6399e+04]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[5.000e+00 2.000e+00 2.500e+01 4.000e+00 3.100e+01 0.000e+00 0.000e+00
  1.000e+00 7.000e+00 4.500e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: attention
Modality: verbal
Role: supervisor
Scene: campus (0)




[WARN] [1723075992.675725656] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[5.8090e+03 2.9000e+01 0.0000e+00 2.9160e+03]
 [4.1097e+04 1.7570e+03 0.0000e+00 5.3000e+01]
 [0.0000e+00 0.0000e+00 2.5793e+04 1.6399e+04]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[5.000e+00 2.000e+00 2.500e+01 4.000e+00 3.100e+01 0.000e+00 0.000e+00
  1.000e+00 8.000e+00 4.510e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: move-in-reverse
Modality: gesture
Role: supervisor
Scene: campus (0)


CLIP SCENE OBSERVATION MODEL
[[5.8420e+03 2.9000e+01 0.0000e+00 2.9870e+03]
 [4.1097e+04 1.7570e+03 0.0000e+00 5.3000e+01]
 [0.0000e+00 0.0000e+00 2.5793e+04 1.6399e+04]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00]]


DPJKU AUDIO SCENE OBS

[WARN] [1723076521.290233474] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[ 9375.  1718.     0.  4746.]
 [41097.  1757.     0.    53.]
 [    0.     0. 25793. 16399.]
 [    0.     0.     0.     0.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[7.000e+00 7.000e+00 2.900e+01 7.000e+00 8.400e+01 1.000e+00 0.000e+00
  1.000e+00 1.900e+01 7.880e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: move-in-reverse
Modality: artag
Role: pedestrian
Scene: campus (0)




[WARN] [1723076525.698268877] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[ 9375.  1777.     0.  4752.]
 [41097.  1757.     0.    53.]
 [    0.     0. 25793. 16399.]
 [    0.     0.     0.     0.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[7.000e+00 7.000e+00 2.900e+01 7.000e+00 8.400e+01 1.000e+00 0.000e+00
  1.000e+00 1.900e+01 7.920e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: move-in-reverse
Modality: artag
Role: pedestrian
Scene: campus (0)




[WARN] [1723076530.138059771] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[ 9375.  1796.     0.  4797.]
 [41097.  1757.     0.    53.]
 [    0.     0. 25793. 16399.]
 [    0.     0.     0.     0.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[7.000e+00 7.000e+00 2.900e+01 7.000e+00 8.400e+01 1.000e+00 0.000e+00
  1.000e+00 2.000e+01 7.950e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: move-in-reverse
Modality: artag
Role: pedestrian
Scene: campus (0)




[WARN] [1723076534.558533592] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[ 9375.  1848.     0.  4806.]
 [41097.  1757.     0.    53.]
 [    0.     0. 25793. 16399.]
 [    0.     0.     0.     0.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[7.000e+00 7.000e+00 2.900e+01 7.000e+00 8.400e+01 1.000e+00 0.000e+00
  1.000e+00 2.100e+01 7.980e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: move-in-reverse
Modality: artag
Role: pedestrian
Scene: campus (0)




[WARN] [1723076538.274133741] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[ 9375.  1910.     0.  4808.]
 [41097.  1757.     0.    53.]
 [    0.     0. 25793. 16399.]
 [    0.     0.     0.     0.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[7.000e+00 7.000e+00 2.900e+01 7.000e+00 8.500e+01 1.000e+00 0.000e+00
  1.000e+00 2.100e+01 8.020e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: move-forward
Modality: artag
Role: pedestrian
Scene: campus (0)




[WARN] [1723076543.140470412] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[ 9375.  1958.     0.  4810.]
 [41097.  1757.     0.    53.]
 [    0.     0. 25793. 16399.]
 [    0.     0.     0.     0.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[7.000e+00 7.000e+00 2.900e+01 7.000e+00 8.500e+01 1.000e+00 0.000e+00
  1.000e+00 2.100e+01 8.050e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: move-forward
Modality: artag
Role: pedestrian
Scene: campus (0)




[WARN] [1723076547.219998476] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[ 9375.  2015.     0.  4810.]
 [41097.  1757.     0.    53.]
 [    0.     0. 25793. 16399.]
 [    0.     0.     0.     0.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[7.000e+00 7.000e+00 2.900e+01 7.000e+00 8.500e+01 1.000e+00 0.000e+00
  1.000e+00 2.100e+01 8.090e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: move-forward
Modality: artag
Role: pedestrian
Scene: campus (0)




[WARN] [1723076551.853691278] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[ 9375.  2057.     0.  4819.]
 [41097.  1757.     0.    53.]
 [    0.     0. 25793. 16399.]
 [    0.     0.     0.     0.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[7.000e+00 7.000e+00 2.900e+01 7.000e+00 8.600e+01 1.000e+00 0.000e+00
  1.000e+00 2.100e+01 8.110e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: move-forward
Modality: artag
Role: pedestrian
Scene: campus (0)




[WARN] [1723076556.289128555] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[ 9375.  2101.     0.  4822.]
 [41097.  1757.     0.    53.]
 [    0.     0. 25793. 16399.]
 [    0.     0.     0.     0.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[7.000e+00 7.000e+00 2.900e+01 7.000e+00 8.700e+01 1.000e+00 0.000e+00
  1.000e+00 2.100e+01 8.130e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: move-forward
Modality: artag
Role: pedestrian
Scene: campus (0)




[WARN] [1723076560.397835772] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[ 9375.  2158.     0.  4822.]
 [41097.  1757.     0.    53.]
 [    0.     0. 25793. 16399.]
 [    0.     0.     0.     0.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[7.000e+00 7.000e+00 2.900e+01 7.000e+00 8.700e+01 1.000e+00 0.000e+00
  1.000e+00 2.100e+01 8.170e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: follow-me
Modality: artag
Role: pedestrian
Scene: campus (0)


CLIP SCENE OBSERVATION MODEL
[[ 9375.  2228.     0.  4838.]
 [41097.  1757.     0.    53.]
 [    0.     0. 25793. 16399.]
 [    0.     0.     0.     0.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[7.000e+00 7.000e+00 2.900e+01 7.000e+00 8.800e+01 1.000e+00 0.000e+00
  1.000e+00 2.100e+01 8.220e+02]
 [2.000e+00 2.87

[WARN] [1723076582.320782011] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[ 9413.  2572.     0.  4848.]
 [41097.  1757.     0.    53.]
 [    0.     0. 25793. 16399.]
 [    0.     0.     0.     0.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[7.000e+00 7.000e+00 2.900e+01 7.000e+00 9.800e+01 1.000e+00 0.000e+00
  1.000e+00 2.100e+01 8.350e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: rally
Modality: artag
Role: pedestrian
Scene: campus (0)




[WARN] [1723076588.472473540] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[ 9413.  2595.     0.  4850.]
 [41097.  1757.     0.    53.]
 [    0.     0. 25793. 16399.]
 [    0.     0.     0.     0.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[7.000e+00 7.000e+00 2.900e+01 7.000e+00 9.900e+01 1.000e+00 0.000e+00
  1.000e+00 2.100e+01 8.360e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: rally
Modality: artag
Role: pedestrian
Scene: campus (0)




[WARN] [1723076591.776602271] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[ 9413.  2624.     0.  4850.]
 [41097.  1757.     0.    53.]
 [    0.     0. 25793. 16399.]
 [    0.     0.     0.     0.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[7.000e+00 7.000e+00 2.900e+01 7.000e+00 9.900e+01 1.000e+00 0.000e+00
  1.000e+00 2.100e+01 8.400e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: rally
Modality: artag
Role: pedestrian
Scene: campus (0)




[WARN] [1723076596.011164367] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[ 9413.  2652.     0.  4850.]
 [41097.  1757.     0.    53.]
 [    0.     0. 25793. 16399.]
 [    0.     0.     0.     0.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[7.000e+00 7.000e+00 2.900e+01 7.000e+00 9.900e+01 1.000e+00 0.000e+00
  1.000e+00 2.100e+01 8.420e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: rally
Modality: artag
Role: pedestrian
Scene: campus (0)




[WARN] [1723076600.117259742] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[ 9414.  2676.     0.  4850.]
 [41097.  1757.     0.    53.]
 [    0.     0. 25793. 16399.]
 [    0.     0.     0.     0.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[7.000e+00 7.000e+00 2.900e+01 7.000e+00 9.900e+01 1.000e+00 0.000e+00
  1.000e+00 2.100e+01 8.440e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: rally
Modality: artag
Role: pedestrian
Scene: campus (0)




[WARN] [1723076603.923936050] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[ 9414.  2709.     0.  4850.]
 [41097.  1757.     0.    53.]
 [    0.     0. 25793. 16399.]
 [    0.     0.     0.     0.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[7.000e+00 7.000e+00 2.900e+01 7.000e+00 9.900e+01 1.000e+00 0.000e+00
  1.000e+00 2.100e+01 8.460e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: halt
Modality: artag
Role: pedestrian
Scene: campus (0)




[WARN] [1723076606.842438042] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[ 9414.  2788.     0.  4851.]
 [41097.  1757.     0.    53.]
 [    0.     0. 25793. 16399.]
 [    0.     0.     0.     0.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[7.000e+00 7.000e+00 2.900e+01 7.000e+00 1.010e+02 1.000e+00 0.000e+00
  1.000e+00 2.100e+01 8.490e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: halt
Modality: artag
Role: pedestrian
Scene: campus (0)




[WARN] [1723076612.103947033] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[ 9414.  2853.     0.  4855.]
 [41097.  1757.     0.    53.]
 [    0.     0. 25793. 16399.]
 [    0.     0.     0.     0.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[7.000e+00 7.000e+00 2.900e+01 7.000e+00 1.010e+02 1.000e+00 0.000e+00
  1.000e+00 2.100e+01 8.530e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: halt
Modality: artag
Role: pedestrian
Scene: campus (0)




[WARN] [1723076616.305077054] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[ 9414.  2927.     0.  4860.]
 [41097.  1757.     0.    53.]
 [    0.     0. 25793. 16399.]
 [    0.     0.     0.     0.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[7.000e+00 7.000e+00 2.900e+01 7.000e+00 1.030e+02 1.000e+00 0.000e+00
  1.000e+00 2.100e+01 8.560e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: halt
Modality: artag
Role: pedestrian
Scene: campus (0)




[WARN] [1723076621.040814435] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[ 9414.  2953.     0.  4910.]
 [41097.  1757.     0.    53.]
 [    0.     0. 25793. 16399.]
 [    0.     0.     0.     0.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[7.000e+00 7.000e+00 2.900e+01 7.000e+00 1.040e+02 1.000e+00 0.000e+00
  1.000e+00 2.100e+01 8.600e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: halt
Modality: artag
Role: pedestrian
Scene: campus (0)




[WARN] [1723076625.749958765] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[ 9414.  3021.     0.  4918.]
 [41097.  1757.     0.    53.]
 [    0.     0. 25793. 16399.]
 [    0.     0.     0.     0.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[7.000e+00 7.000e+00 2.900e+01 7.000e+00 1.040e+02 1.000e+00 0.000e+00
  1.000e+00 2.100e+01 8.650e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: advance
Modality: artag
Role: pedestrian
Scene: campus (0)




[WARN] [1723076631.963111919] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[ 9414.  3030.     0.  4918.]
 [41097.  1757.     0.    53.]
 [    0.     0. 25793. 16399.]
 [    0.     0.     0.     0.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[7.000e+00 7.000e+00 2.900e+01 7.000e+00 1.040e+02 1.000e+00 0.000e+00
  1.000e+00 2.100e+01 8.660e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: advance
Modality: artag
Role: pedestrian
Scene: campus (0)




[WARN] [1723076635.841152790] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[ 9414.  3036.     0.  4919.]
 [41097.  1757.     0.    53.]
 [    0.     0. 25793. 16399.]
 [    0.     0.     0.     0.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[7.000e+00 7.000e+00 2.900e+01 7.000e+00 1.040e+02 1.000e+00 0.000e+00
  1.000e+00 2.100e+01 8.670e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: advance
Modality: artag
Role: pedestrian
Scene: campus (0)




[WARN] [1723076639.203485984] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[ 9414.  3055.     0.  4919.]
 [41097.  1757.     0.    53.]
 [    0.     0. 25793. 16399.]
 [    0.     0.     0.     0.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[7.000e+00 7.000e+00 2.900e+01 7.000e+00 1.040e+02 1.000e+00 0.000e+00
  1.000e+00 2.100e+01 8.680e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: advance
Modality: artag
Role: pedestrian
Scene: campus (0)




[WARN] [1723076643.195594694] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[ 9414.  3069.     0.  4919.]
 [41097.  1757.     0.    53.]
 [    0.     0. 25793. 16399.]
 [    0.     0.     0.     0.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[7.000e+00 7.000e+00 2.900e+01 7.000e+00 1.040e+02 1.000e+00 0.000e+00
  1.000e+00 2.100e+01 8.690e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: advance
Modality: artag
Role: pedestrian
Scene: campus (0)




[WARN] [1723076647.154137619] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[ 9414.  3075.     0.  4920.]
 [41097.  1757.     0.    53.]
 [    0.     0. 25793. 16399.]
 [    0.     0.     0.     0.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[7.000e+00 7.000e+00 2.900e+01 7.000e+00 1.040e+02 1.000e+00 0.000e+00
  1.000e+00 2.100e+01 8.700e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: attention
Modality: artag
Role: pedestrian
Scene: campus (0)




[WARN] [1723076649.455212749] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[ 9414.  3117.     0.  4920.]
 [41097.  1757.     0.    53.]
 [    0.     0. 25793. 16399.]
 [    0.     0.     0.     0.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[7.000e+00 7.000e+00 2.900e+01 7.000e+00 1.040e+02 1.000e+00 0.000e+00
  1.000e+00 2.100e+01 8.740e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: attention
Modality: artag
Role: pedestrian
Scene: campus (0)




[WARN] [1723076653.771489861] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[ 9414.  3145.     0.  4930.]
 [41097.  1757.     0.    53.]
 [    0.     0. 25793. 16399.]
 [    0.     0.     0.     0.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[7.000e+00 7.000e+00 2.900e+01 7.000e+00 1.040e+02 1.000e+00 0.000e+00
  1.000e+00 2.200e+01 8.760e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: attention
Modality: artag
Role: pedestrian
Scene: campus (0)




[WARN] [1723076657.800239234] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[ 9414.  3187.     0.  4930.]
 [41097.  1757.     0.    53.]
 [    0.     0. 25793. 16399.]
 [    0.     0.     0.     0.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[7.000e+00 7.000e+00 2.900e+01 7.000e+00 1.040e+02 1.000e+00 0.000e+00
  1.000e+00 2.200e+01 8.790e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: attention
Modality: artag
Role: pedestrian
Scene: campus (0)




[WARN] [1723076662.075407764] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[ 9414.  3222.     0.  4933.]
 [41097.  1757.     0.    53.]
 [    0.     0. 25793. 16399.]
 [    0.     0.     0.     0.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[7.000e+00 7.000e+00 2.900e+01 7.000e+00 1.040e+02 1.000e+00 0.000e+00
  1.000e+00 2.200e+01 8.810e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: attention
Modality: artag
Role: pedestrian
Scene: campus (0)




[WARN] [1723076666.021003299] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[ 9414.  3239.     0.  4960.]
 [41097.  1757.     0.    53.]
 [    0.     0. 25793. 16399.]
 [    0.     0.     0.     0.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[7.000e+00 7.000e+00 2.900e+01 7.000e+00 1.040e+02 1.000e+00 0.000e+00
  1.000e+00 2.200e+01 8.840e+02]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00 0.000e+00]]


Command: move-in-reverse
Modality: verbal
Role: pedestrian
Scene: campus (0)


CLIP SCENE OBSERVATION MODEL
[[ 9501.  3252.     0.  4962.]
 [41097.  1757.     0.    53.]
 [    0.     0. 25793. 16399.]
 [    0.     0.     0.     0.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[7.000e+00 7.000e+00 2.900e+01 7.000e+00 1.040e+02 1.000e+00 0.000e+00
  1.000e+00 2.200e+01 8.840e+02]
 [2.000e+

[WARN] [1723078417.982556554] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[25007.  5983.     0.  7662.]
 [41097.  1757.     0.    53.]
 [    0.     0. 25793. 16399.]
 [    0.     0.     0.  7084.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[1.400e+01 1.500e+01 4.100e+01 9.000e+00 1.950e+02 4.000e+00 1.000e+00
  1.000e+00 5.500e+01 1.943e+03]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [1.100e+01 1.900e+01 3.400e+01 4.700e+01 2.340e+02 0.000e+00 6.000e+00
  0.000e+00 6.000e+00 5.600e+01]]


Command: move-in-reverse
Modality: verbal
Role: supervisor
Scene: lobby (3)




[WARN] [1723078422.037024190] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[25007.  5983.     0.  7662.]
 [41097.  1757.     0.    53.]
 [    0.     0. 25793. 16399.]
 [    0.     0.     0.  7135.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[1.400e+01 1.500e+01 4.100e+01 9.000e+00 1.950e+02 4.000e+00 1.000e+00
  1.000e+00 5.500e+01 1.943e+03]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [1.100e+01 2.000e+01 3.500e+01 4.700e+01 2.340e+02 0.000e+00 6.000e+00
  0.000e+00 6.000e+00 5.700e+01]]


Command: move-in-reverse
Modality: verbal
Role: supervisor
Scene: lobby (3)




[WARN] [1723078437.009294886] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[25007.  5983.     0.  7662.]
 [41097.  1757.     0.    53.]
 [    0.     0. 25793. 16399.]
 [    0.     0.     0.  7164.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[1.400e+01 1.500e+01 4.100e+01 9.000e+00 1.950e+02 4.000e+00 1.000e+00
  1.000e+00 5.500e+01 1.943e+03]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [1.100e+01 2.000e+01 3.500e+01 4.800e+01 2.350e+02 0.000e+00 6.000e+00
  0.000e+00 6.000e+00 5.700e+01]]


Command: move-in-reverse
Modality: verbal
Role: supervisor
Scene: lobby (3)




[WARN] [1723078439.966775088] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[25007.  5983.     0.  7662.]
 [41097.  1757.     0.    53.]
 [    0.     0. 25793. 16399.]
 [    0.     0.     0.  7187.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[1.400e+01 1.500e+01 4.100e+01 9.000e+00 1.950e+02 4.000e+00 1.000e+00
  1.000e+00 5.500e+01 1.943e+03]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [1.100e+01 2.000e+01 3.500e+01 4.800e+01 2.360e+02 0.000e+00 6.000e+00
  0.000e+00 6.000e+00 5.700e+01]]


Command: move-in-reverse
Modality: verbal
Role: supervisor
Scene: lobby (3)


CLIP SCENE OBSERVATION MODEL
[[25007.  5983.     0.  7662.]
 [41097.  1757.     0.    53.]
 [    0.     0. 25793. 16399.]
 [    0.     0.     0.  7273.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[1.400e+01 1.500e+01 4.100e+01 9.000e+00 1.950e+02 4.000e+00 1.000e+00
  1.000e+00 5.500e+01 1.943e+03]
 [2.000e+0

[WARN] [1723078548.005869037] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[25007.  5983.     0.  7662.]
 [41097.  1757.     0.    53.]
 [    0.     0. 25793. 16399.]
 [    0.     0.     0.  8288.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[1.400e+01 1.500e+01 4.100e+01 9.000e+00 1.950e+02 4.000e+00 1.000e+00
  1.000e+00 5.500e+01 1.943e+03]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [1.500e+01 2.300e+01 4.400e+01 5.700e+01 2.650e+02 0.000e+00 6.000e+00
  0.000e+00 6.000e+00 6.900e+01]]


Command: rally
Modality: verbal
Role: supervisor
Scene: lobby (3)




[WARN] [1723078548.502572171] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[25007.  5983.     0.  7662.]
 [41097.  1757.     0.    53.]
 [    0.     0. 25793. 16399.]
 [    0.     0.     0.  8297.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[1.400e+01 1.500e+01 4.100e+01 9.000e+00 1.950e+02 4.000e+00 1.000e+00
  1.000e+00 5.500e+01 1.943e+03]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [1.500e+01 2.300e+01 4.400e+01 5.700e+01 2.650e+02 0.000e+00 6.000e+00
  0.000e+00 6.000e+00 7.000e+01]]


Command: rally
Modality: verbal
Role: supervisor
Scene: lobby (3)




[WARN] [1723078550.899777207] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[25007.  5983.     0.  7662.]
 [41097.  1757.     0.    53.]
 [    0.     0. 25793. 16399.]
 [    0.     0.     0.  8314.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[1.400e+01 1.500e+01 4.100e+01 9.000e+00 1.950e+02 4.000e+00 1.000e+00
  1.000e+00 5.500e+01 1.943e+03]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [1.500e+01 2.300e+01 4.400e+01 5.700e+01 2.670e+02 0.000e+00 6.000e+00
  0.000e+00 6.000e+00 7.000e+01]]


Command: rally
Modality: verbal
Role: supervisor
Scene: lobby (3)


CLIP SCENE OBSERVATION MODEL
[[25007.  5983.     0.  7662.]
 [41097.  1757.     0.    53.]
 [    0.     0. 25793. 16399.]
 [    0.     0.     0.  8318.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[1.400e+01 1.500e+01 4.100e+01 9.000e+00 1.950e+02 4.000e+00 1.000e+00
  1.000e+00 5.500e+01 1.943e+03]
 [2.000e+00 2.870e+0

[WARN] [1723078551.647376773] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order
[WARN] [1723078551.977502463] [rosbag2_storage_mcap]: no message indices found, falling back to reading in file order


CLIP SCENE OBSERVATION MODEL
[[25007.  5983.     0.  7662.]
 [41097.  1757.     0.    53.]
 [    0.     0. 25793. 16399.]
 [    0.     0.     0.  8332.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[1.400e+01 1.500e+01 4.100e+01 9.000e+00 1.950e+02 4.000e+00 1.000e+00
  1.000e+00 5.500e+01 1.943e+03]
 [2.000e+00 2.870e+02 1.000e+01 1.000e+01 7.950e+02 1.000e+00 0.000e+00
  1.000e+00 1.000e+01 1.349e+03]
 [1.000e+01 1.700e+02 2.109e+03 4.000e+01 8.000e+01 0.000e+00 0.000e+00
  0.000e+00 6.300e+01 2.500e+01]
 [1.500e+01 2.300e+01 4.500e+01 5.700e+01 2.680e+02 0.000e+00 6.000e+00
  0.000e+00 6.000e+00 7.000e+01]]


Command: halt
Modality: verbal
Role: supervisor
Scene: lobby (3)


CLIP SCENE OBSERVATION MODEL
[[25007.  5983.     0.  7662.]
 [41097.  1757.     0.    53.]
 [    0.     0. 25793. 16399.]
 [    0.     0.     0.  8417.]]


DPJKU AUDIO SCENE OBSERVATION MODEL
[[1.400e+01 1.500e+01 4.100e+01 9.000e+00 1.950e+02 4.000e+00 1.000e+00
  1.000e+00 5.500e+01 1.943e+03]
 [2.000e+00 2.870e+02